# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-push, pre-commit]
default_install_hook_types: [pre-push, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push, pre-commit]
      - id: end-of-file-fixer
        stages: [pre-push, pre-commit]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        additional_dependencies:
          - pylint-per-file-ignores
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args:
          - --style
          - yapf
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        exclude: (?x)(.*test.*\.py$|venv/|backtest/|valuation_table/)
        additional_dependencies: [pydantic, types-requests, pandas-stubs]
