# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-push, pre-commit]
default_install_hook_types: [pre-push, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push, pre-commit]
      - id: end-of-file-fixer
        stages: [pre-push, pre-commit]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        additional_dependencies:
          - pylint-per-file-ignores
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args:
          - --style
          - yapf
